### ISSUE TITLE
 Cannot find module 'tslib' from 'node_modules/ts-results/index.js' when running Jest test

### ISSUE THREAD

**Issue by afalahi** [vultix/ts-results#54]
Version:
ts-results 3.3.0 (latest)

Stacktrace:
```console
    Require stack:
      node_modules/ts-results/index.js
      src/controllers/ConfigurationManager/classes/Profile.ts
      src/controllers/ConfigurationManager/tests/configManager.test.ts

       6 | } from '../../../utils/errorMessages';
       7 | import ConfigProfile from '../interfaces/ConfigProfile';
    >  8 | import { Result, Ok, Err } from 'ts-results';
         | ^
       9 |
      10 | export default class Profile {
      11 |   private profiles: ConfigProfile = {};

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:487:11)
      at node_modules/ts-results/index.js:12:19
      at node_modules/ts-results/index.js:3:17
      at Object.<anonymous> (node_modules/ts-results/index.js:9:3)
      at Object.<anonymous> (src/controllers/ConfigurationManager/classes/Profile.ts:8:1)
      at Object.<anonymous> (src/controllers/ConfigurationManager/tests/configManager.test.ts:2:1)
```

**Comment by wralith** [comment]
https://github.com/vultix/ts-results/pull/38 Waiting for new release i guess

**Comment by jstasiak** [comment]
For what it's worth we (Lune Climate) maintain a `ts-results` fork where this is resolved: https://www.npmjs.com/package/ts-results-es
